// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABH8ONWLX40FaPEBFZdWK01SglYWm9p8k',
    appId: '1:260166625635:web:c6f717d9c7d38c4f79cb56',
    messagingSenderId: '260166625635',
    projectId: 'compy-tcc',
    authDomain: 'compy-tcc.firebaseapp.com',
    storageBucket: 'compy-tcc.firebasestorage.app',
    measurementId: 'G-D765ECKZVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanHcCAyv83nRMmGR459H80ynK9VrniBo',
    appId: '1:260166625635:android:d3a540c67965084979cb56',
    messagingSenderId: '260166625635',
    projectId: 'compy-tcc',
    storageBucket: 'compy-tcc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpIgpFeuhyh9ikCh13QjQv9oNqEXMF_xk',
    appId: '1:260166625635:ios:d62c9231b41ba05179cb56',
    messagingSenderId: '260166625635',
    projectId: 'compy-tcc',
    storageBucket: 'compy-tcc.firebasestorage.app',
    androidClientId: '260166625635-f84d9ct7og1hr3o0cb96l3q5707jmf15.apps.googleusercontent.com',
    iosClientId: '260166625635-9nit402v07556fc2ovp039qinlcvd6c1.apps.googleusercontent.com',
    iosBundleId: 'br.com.compy.app',
  );
}
